/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jniandndk_MyJniU */

#ifndef _Included_jniandndk_MyJniU
#define _Included_jniandndk_MyJniU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jniandndk_MyJniU
 * Method:    show
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jniandndk_MyJniU_show
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
